# Generated by Django 5.0.14 on 2026-04-02 03:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, default='')),
                ('cor', models.CharField(default='#007bff', max_length=7)),
                ('icone', models.CharField(default='bi-file-text', max_length=50)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documentos.categoriadocumento')),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documentos',
                'db_table': 'categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('PETICAO', 'Petição'), ('CONTRATO', 'Contrato'), ('PROCURACAO', 'Procuração'), ('CERTIDAO', 'Certidão'), ('OFICIO', 'Ofício'), ('ATA', 'Ata'), ('PARECER', 'Parecer'), ('RELATORIO', 'Relatório'), ('COMPROVANTE', 'Comprovante'), ('OUTRO', 'Outro')], max_length=20)),
                ('arquivo', models.FileField(upload_to=documentos.models.upload_documento_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'])])),
                ('tamanho_arquivo', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em Revisão'), ('APROVADO', 'Aprovado'), ('ASSINADO', 'Assinado'), ('ENVIADO', 'Enviado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=15)),
                ('confidencialidade', models.CharField(choices=[('PUBLICO', 'Público'), ('INTERNO', 'Interno'), ('CONFIDENCIAL', 'Confidencial'), ('SECRETO', 'Secreto')], default='INTERNO', max_length=15)),
                ('versao', models.CharField(default='1.0', max_length=10)),
                ('data_documento', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('palavras_chave', models.CharField(blank=True, default='', max_length=500)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('publico', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_autor', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.categoriadocumento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cliente', to='clientes.cliente')),
                ('documento_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documentos.documento')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_processo', to='processos.processo')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisor', to=settings.AUTH_USER_MODEL)),
                ('usuarios_acesso', models.ManyToManyField(blank=True, related_name='documentos_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ASSINADO', 'Assinado'), ('REJEITADO', 'Rejeitado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=15)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('certificado_digital', models.TextField(blank=True, default='')),
                ('hash_assinatura', models.CharField(blank=True, default='', max_length=128)),
                ('motivo_rejeicao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('signatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.documento')),
            ],
            options={
                'verbose_name': 'Assinatura Digital',
                'verbose_name_plural': 'Assinaturas Digitais',
                'db_table': 'assinatura_digital',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='LogAcessoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acao', models.CharField(choices=[('VISUALIZAR', 'Visualizar'), ('DOWNLOAD', 'Download'), ('EDITAR', 'Editar'), ('COMPARTILHAR', 'Compartilhar'), ('ASSINAR', 'Assinar'), ('EXCLUIR', 'Excluir')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.JSONField(default=dict)),
                ('sucesso', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso a Documento',
                'verbose_name_plural': 'Logs de Acesso a Documentos',
                'db_table': 'log_acesso',
                'ordering': ['-data_acesso'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('PETICAO_INICIAL', 'Petição Inicial'), ('CONTESTACAO', 'Contestação'), ('RECURSO', 'Recurso'), ('CONTRATO_PRESTACAO', 'Contrato de Prestação de Serviços'), ('PROCURACAO', 'Procuração'), ('OFICIO', 'Ofício'), ('ATA_REUNIAO', 'Ata de Reunião'), ('PARECER_JURIDICO', 'Parecer Jurídico'), ('OUTRO', 'Outro')], max_length=30)),
                ('arquivo_template', models.FileField(upload_to='templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'odt'])])),
                ('variaveis', models.JSONField(default=list)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentos.categoriadocumento')),
            ],
            options={
                'verbose_name': 'Template de Documento',
                'verbose_name_plural': 'Templates de Documentos',
                'db_table': 'template',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['cliente', 'ativo'], name='documento_cliente_45c3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['processo', 'ativo'], name='documento_process_667698_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['status'], name='documento_status_3fd292_idx'),
        ),
        migrations.AddConstraint(
            model_name='assinaturadigital',
            constraint=models.UniqueConstraint(fields=('documento', 'signatario'), name='unique_documento_signatario'),
        ),
    ]
