# Generated by Django 5.0.14 on 2026-04-05 04:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_registro', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True, default='')),
                ('arquivo', models.FileField(upload_to='documentos/usuarios/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Usuário',
                'verbose_name_plural': 'Documentos de Usuários',
                'db_table': 'config_documento_usuario',
                'ordering': ['-data_registro'],
                'indexes': [models.Index(fields=['usuario', 'ativo'], name='config_docu_usuario_14fc11_idx')],
            },
        ),
    ]
