# Generated by Django 5.0.14 on 2026-04-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, default='', max_length=50)),
                ('contato', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedores',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['ativo', 'nome'], name='fornecedore_ativo_03ae79_idx'), models.Index(fields=['documento'], name='fornecedore_documen_5e9b33_idx')],
            },
        ),
    ]
