# Generated by Django 5.0.14 on 2026-04-02 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_processo', models.CharField(max_length=50, unique=True)),
                ('tarefa', models.CharField(blank=True, default='', max_length=200)),
                ('foro', models.CharField(blank=True, default='padrao', max_length=200)),
                ('vara', models.CharField(blank=True, default='padrao', max_length=200)),
                ('comarca', models.CharField(blank=True, default='padrao', max_length=200)),
                ('classe', models.CharField(blank=True, default='padrao', max_length=200)),
                ('assunto', models.CharField(blank=True, default='padrao', max_length=500)),
                ('parte_contraria', models.CharField(blank=True, default='padrao', max_length=200)),
                ('situacao_atual', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ANDAMENTO', 'Em Andamento'), ('SUSPENSO', 'Suspenso'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='NOVO', max_length=20)),
                ('risco', models.CharField(choices=[('BAIXO', 'Baixo'), ('MEDIO', 'Médio'), ('ALTO', 'Alto')], default='MEDIO', max_length=10)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('prazo_final', models.DateTimeField(blank=True, null=True)),
                ('advogado_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'db_table': 'processos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['numero_processo'], name='processos_numero__f3f191_idx'), models.Index(fields=['cliente', 'ativo'], name='processos_cliente_8e4a75_idx'), models.Index(fields=['status', 'prazo_final'], name='processos_status_4c081c_idx')],
            },
        ),
    ]
