# Generated by Django 5.0.14 on 2026-04-02 03:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, default='', max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, default='', max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_informar', 'Não Informar')], default='nao_informar', max_length=15)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], default='', max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='advogados/fotos/')),
                ('telefone_celular', models.CharField(blank=True, default='', max_length=20)),
                ('telefone_fixo', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('email_citacao', models.EmailField(blank=True, default='', max_length=100)),
                ('cep', models.CharField(blank=True, default='', max_length=10)),
                ('logradouro', models.CharField(blank=True, default='', max_length=100)),
                ('numero', models.CharField(blank=True, default='', max_length=10)),
                ('complemento', models.CharField(blank=True, default='', max_length=50)),
                ('bairro', models.CharField(blank=True, default='', max_length=50)),
                ('cidade', models.CharField(blank=True, default='', max_length=50)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('oab_numero', models.CharField(blank=True, default='', max_length=20)),
                ('oab_uf', models.CharField(blank=True, default='', max_length=2)),
                ('area_atuacao_principal', models.CharField(blank=True, default='', max_length=100)),
                ('especialidades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('descricao_profissional', models.TextField(blank=True, default='')),
                ('nivel_profissional', models.CharField(choices=[('estagiario', 'Estagiário(a)'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('socio', 'Sócio(a)')], default='junior', max_length=20)),
                ('cargo', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('clt', 'CLT'), ('pj', 'Pessoa Jurídica'), ('associado', 'Associado'), ('freelancer', 'Freelancer')], default='', max_length=20)),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pix_chave', models.CharField(blank=True, default='', max_length=120)),
                ('banco_nome', models.CharField(blank=True, default='', max_length=50)),
                ('agencia', models.CharField(blank=True, default='', max_length=10)),
                ('conta', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_conta', models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança')], default='', max_length=20)),
                ('cpf_cnpj_conta', models.CharField(blank=True, default='', max_length=20)),
                ('documentos_pendentes', models.BooleanField(default=False)),
                ('termo_assinado', models.BooleanField(default=False)),
                ('curriculo_pdf', models.FileField(blank=True, null=True, upload_to='advogados/curriculos/')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advogados_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advogado',
                'verbose_name_plural': 'Advogados',
                'db_table': 'advogado',
                'ordering': ['nome', 'sobrenome'],
            },
        ),
    ]
