# Generated by Django 5.0.14 on 2026-04-02 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='advogados', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='advogado',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisionados', to='accounts.advogado'),
        ),
        migrations.AddField(
            model_name='advogado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_advogado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='advogado',
            index=models.Index(fields=['ativo', 'nivel_profissional'], name='advogado_ativo_044558_idx'),
        ),
        migrations.AddConstraint(
            model_name='advogado',
            constraint=models.UniqueConstraint(condition=models.Q(('oab_numero', ''), _negated=True), fields=('oab_numero', 'oab_uf'), name='unique_advogado_oab'),
        ),
    ]
