# Generated by Django 5.0.14 on 2026-04-02 03:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'db_table': 'conta_bancaria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('PATRIMONIO', 'Patrimônio')], max_length=15)),
                ('conta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.planocontas')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Plano de Contas',
                'db_table': 'plano_contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('TRANSFERENCIA', 'Transferência')], max_length=15)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('parcelamento', models.CharField(choices=[('AVISTA', 'À Vista'), ('2X', '2x'), ('3X', '3x'), ('4X', '4x'), ('5X', '5x'), ('6X', '6x'), ('7X', '7x'), ('8X', '8x'), ('9X', '9x'), ('10X', '10x'), ('11X', '11x'), ('12X', '12x'), ('13X', '13x'), ('14X', '14x'), ('15X', '15x'), ('16X', '16x'), ('17X', '17x'), ('18X', '18x'), ('19X', '19x'), ('20X', '20x'), ('21X', '21x'), ('22X', '22x'), ('23X', '23x'), ('24X', '24x')], default='AVISTA', max_length=20)),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('competencia_inicio', models.DateField(blank=True, null=True)),
                ('competencia_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/')),
                ('numero_documento', models.CharField(blank=True, default='', max_length=50)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.processo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plano_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.planocontas')),
            ],
            options={
                'verbose_name': 'Movimentação Financeira',
                'verbose_name_plural': 'Movimentações Financeiras',
                'db_table': 'movimentacao',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual'), ('HORA', 'Por Hora'), ('EXITO', 'Êxito')], max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horas_trabalhadas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_orcamento', models.DateField(default=django.utils.timezone.now)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('APROVADO', 'Aprovado'), ('FATURADO', 'Faturado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=15)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('numero_documento', models.CharField(blank=True, default='', max_length=50)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.processo')),
            ],
            options={
                'verbose_name': 'Honorário',
                'verbose_name_plural': 'Honorários',
                'db_table': 'honorario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cliente', 'status'], name='honorario_cliente_657d85_idx'), models.Index(fields=['advogado', 'ativo'], name='honorario_advogad_ea32db_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='planocontas',
            index=models.Index(fields=['ativo', 'tipo'], name='plano_conta_ativo_d84daf_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['conta_bancaria', 'data_pagamento'], name='movimentaca_conta_b_e66b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['status', 'data_vencimento'], name='movimentaca_status_9a1f41_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['cliente', 'ativo'], name='movimentaca_cliente_d4fc60_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['fornecedor', 'ativo'], name='movimentaca_fornece_c95d69_idx'),
        ),
    ]
