# Generated by Django 5.0.14 on 2026-04-02 03:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone_whatsapp', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('consentimento_lgpd', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('data_consentimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Consentimento')),
                ('documento_pendente', models.BooleanField(default=False)),
                ('tipos_documento', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Categorias de documento associadas ao cliente', size=None)),
                ('canal_preferido', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], default='whatsapp', max_length=10, verbose_name='Canal Preferido')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('advogado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.advogado')),
                ('usuarios', models.ManyToManyField(blank=True, help_text='Usuários que têm acesso a este cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Vinculados')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
