# Generated by Django 5.0.14 on 2026-04-02 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndamentoProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(choices=[('PETICAO', 'Petição'), ('AUDIENCIA_MARCADA', 'Audiência Marcada'), ('SENTENCA_PUBLICADA', 'Sentença Publicada'), ('DOCUMENTO_SOLICITADO', 'Documento Solicitado'), ('ANDAMENTO_GERAL', 'Andamento Geral')], default='ANDAMENTO_GERAL', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_evento', models.DateTimeField()),
                ('prazo_limite', models.DateTimeField(blank=True, null=True)),
                ('publicado_para_cliente', models.BooleanField(default=False)),
                ('canal_enviado', models.JSONField(blank=True, default=dict)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='andamentos', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Andamento Processual',
                'verbose_name_plural': 'Andamentos Processuais',
                'db_table': 'processos_andamento_processual',
                'ordering': ['-data_evento'],
                'indexes': [models.Index(fields=['processo', 'data_evento'], name='processos_a_process_b9a889_idx'), models.Index(fields=['ativo', 'tipo_evento'], name='processos_a_ativo_44337c_idx')],
            },
        ),
    ]
