# Generated by Django 5.0.14 on 2025-10-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], max_length=10, verbose_name='Canal')),
                ('evento', models.CharField(choices=[('peticao', 'Petição'), ('audiencia_marcada', 'Audiência Marcada'), ('sentenca_publicada', 'Sentença Publicada'), ('documento_solicitado', 'Documento Solicitado'), ('andamento_geral', 'Andamento Geral'), ('resumo_semanal', 'Resumo Semanal')], max_length=30, verbose_name='Evento')),
                ('linguagem', models.CharField(default='pt-BR', max_length=10, verbose_name='Linguagem')),
                ('conteudo', models.TextField(help_text='Use placeholders como {{primeiro_nome}}, {{numero_processo}}, {{data_evento_fmt}}', verbose_name='Conteúdo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagem',
                'ordering': ['canal', 'evento'],
                'unique_together': {('canal', 'evento', 'linguagem')},
            },
        ),
    ]
