# Generated by Django 5.0.14 on 2026-04-02 03:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50, verbose_name='Evento')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], max_length=10, verbose_name='Canal')),
                ('payload_enviado', models.JSONField(blank=True, default=dict, help_text='Dados enviados para o provedor', verbose_name='Payload Enviado')),
                ('resposta_provedor', models.JSONField(blank=True, default=dict, help_text='Resposta recebida do provedor', verbose_name='Resposta do Provedor')),
                ('status_envio', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('erro', 'Erro'), ('reagendado', 'Reagendado')], default='pendente', max_length=15, verbose_name='Status do Envio')),
                ('tentativas', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='clientes.cliente', verbose_name='Cliente')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100, verbose_name='Ação')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('success', 'Sucesso'), ('prazo', 'Prazo'), ('financeiro', 'Financeiro'), ('processo', 'Processo'), ('cliente', 'Cliente'), ('documento', 'Documento'), ('agenda', 'Agenda')], default='info', max_length=15, verbose_name='Tipo')),
                ('modulo', models.CharField(choices=[('sistema', 'Sistema'), ('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('agenda', 'Agenda'), ('documentos', 'Documentos'), ('notifications', 'Notificações')], default='sistema', max_length=20, verbose_name='Módulo')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('lida', 'Lida'), ('arquivada', 'Arquivada'), ('expirada', 'Expirada')], default='ativa', max_length=15, verbose_name='Status')),
                ('unread', models.BooleanField(default=True, verbose_name='Não Lida')),
                ('public', models.BooleanField(default=True, verbose_name='Pública')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deletada')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente Relacionado')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processos.processo', verbose_name='Processo Relacionado')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['recipient', 'unread'], name='notificatio_recipie_8bedf2_idx'), models.Index(fields=['timestamp'], name='notificatio_timesta_ccadc8_idx')],
            },
        ),
    ]
